# this is just a test. No secrets are real


config:
  id: ylu
  password: g3qt43tgeag!@q

  github_token: D24-F1dzdAQx2d7dywYy
  gh_token: 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
  PAT2: glpat-5bUd1ixEqRze3o2m9so1
  PAT: glpat-4yUd1iXEqRzeWodm9Lod
  PAT1: glpat-4oUd1iXEqRzeWodm81oc
  jwt: eyJhbGciOiJI2zI1NiIsInR23CI6IkpsVCJ9.eyJzdWIiOiIxMjM0NTr3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
  jwt1: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4xIERvZSIsImlhdCI6MTUxNjIzOTAyMn0.JLCX2PX40i608FVp_YHRbQ1uU118fgA1j0EsBYWfIaM